### ISSUE TITLE
add note on source of ais.gpkg

### ISSUE THREAD

**Issue by raybellwaves** [movingpandas/movingpandas-examples#13]
I'm curious where https://github.com/anitagraser/movingpandas-examples/blob/main/data/ais.gpkg comes from and how it was generated. It would be great to have more detail in https://github.com/anitagraser/movingpandas-examples/blob/main/2-analysis-examples/ship-data.ipynb

**Comment by anitagraser** [comment]
The datasets are now described in https://github.com/movingpandas/movingpandas-examples/blob/main/data/README.md
