### ISSUE TITLE
Aggregating trajectories in tutorial 9 does not work

### ISSUE THREAD

**Issue by holezekki99** [movingpandas/movingpandas-examples#25]
I was facing this same error on my own project.

When running the tutorial 9 on binder notebook, cell:
aggregator = mpd.TrajectoryCollectionAggregator(generalized, max_distance=1000, min_distance=100, min_stop_duration=timedelta(minutes=5))

results:
error: AttributeError: 'GeoSeries' object has no attribute 'iteritems'

https://github.com/movingpandas/movingpandas-examples/blob/main/1-tutorials/9-aggregating-trajectories.ipynb

**Comment by anitagraser** [comment]
Thank you for your report. Which library versions are you using? For reference, here you can see a working environment: 
https://movingpandas.github.io/movingpandas-website/1-tutorials/9-aggregating-trajectories.html

**Comment by holezekki99** [comment]
After installing v0.16.0 to a clean conda environment (and installing other relvant missing packages) it looks like the TrajectoryCollectionAggregator function is working as expected.
