### ISSUE TITLE
Exception: An axis may only be assigned one projection type

### ISSUE THREAD

**Issue by wongimae** [movingpandas/movingpandas-examples#28]
After following the tutorial on Getting Started, I was unable to successfully run

`my_traj.hvplot(line_width=7.0, tiles='OSM')`

which gave "Exception: An axis may only be assigned one projection type"

Attached below is my system info
![image](https://github.com/movingpandas/movingpandas-examples/assets/50194595/4a518bb5-1df0-4c7a-8dd1-6f953ce97bd9)

**Comment by anitagraser** [comment]
There is an issue with hvplot 0.8.4. Please downgrade to 0.8.3

**Comment by wongimae** [comment]
Oh that solved it. Thanks
