### ISSUE TITLE
ValueError: Latitude must be in the [-90; 90] range.

### ISSUE THREAD

**Issue by wongimae** [movingpandas/movingpandas-examples#29]
I tried to run the code below
```python
gdf = gpd.read_file('geolife_small.gpkg')
gdf
tc = mpd.TrajectoryCollection(gdf, 'trajectory_id', t='t')

my_traj = tc.trajectories[0]
my_traj
detector = mpd.TrajectoryStopDetector(my_traj)
stop_time_ranges = detector.get_stop_time_ranges(min_duration=timedelta(seconds=60), max_diameter=100)
```
Essentially following the tutorial on stop detection with single trajectory.
But I got ValueError: Latitude must be in the [-90; 90] range.

This is not an issue when the longitude value is less than 90.

**Comment by anitagraser** [comment]
Yes,  this is a known issue which I've fixed recently https://github.com/movingpandas/movingpandas/issues/336

Please stay tuned for the new release in the upcoming days

**Comment by wongimae** [comment]
Great, thanks so much. Looking forward
